name: Deployment

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh to server
        uses: appleboy/ssh-action@master
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker service update --image ${{secrets.DOCKER_USERNAME}}/xendit-webhook:${{env.VER}} --force common-services_whoami-1
