name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
    - uses: actions/checkout@v3
    - name: set variables
      run: |
        VERSION=$(cat .version) 
        echo "VER=$VERSION" >> $GITHUB_ENV 
    - name: docker login
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: build the docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/xendit-webhook:${{env.VER}}
    - name: push to dockerhub
      run: docker push ${{secrets.DOCKER_USERNAME}}/xendit-webhook:${{env.VER}}
